version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    environment:
      HOST_DB: db:3306
    networks:
      - app-network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-network
      - app-network-2
    volumes:
      - db-data:/var/lib/mysql
  web2:
    image: nginx
    ports:
      - "8080:80"
    environment:
      HOST_DB: db:3306
    networks:
      - app-network-2
networks:
  app-network:
  app-network-2:
volumes:
  db-data:
